trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'build'
    jobs:
      - job: 'buildjob'
        steps:
          - task:
            inputs:
              mavenPomFile: pom.xml
              goals: package
              publishJUitResults: true
              testResultsFiles: '**/surefire-reports/*.xml'           
